### PR TITLE
Small prettifications

### PR DESCRIPTION
**Pull request by jaseg**
Hi,

thanks for putting this on github. I had a read through it and I kind of like it.

This PR contains three largely separate changes that I think make sense:
* Put globals into thread-local storage to make stuff work with multithreading
* Use more context managers to make some parts more readable
* Replace lots of asserts with exceptions containing helpful error messages

Please, tell me what you think of these. If necessary I can split this up into separate PRs.

### CODE REVIEW

**Comment by dvc94ch** [comment]
Can you rebase? The context manager stuff seems like an improvement, and we def. want better error messages. Not sure if putting the globals in tls is necessary based on how it's intended to be used.

**Comment by jaseg** [comment]
Ok, I have rebased your commits on top of mine since the line wrapping commit would have been more annoying to merge the other way around.

I don't think the TLS thing is strictly necessary either, but it's only 20loc, it nicely encapsulates all global state and it might at some point save somebody a lot of head-scratching. One situation I could imagine it could come in handy is parallel multi-threaded builds.

**Comment by dvc94ch** [comment]
force pushing to master is a bad idea since it breaks all cloned git repos - fyi: it's ok in dev branches

**Comment by dvc94ch** [comment]
Please open a new PR for the README changes so that I can merge them. Closing PR for now. Thanks!

**Pull request closed without merging**
